### ISSUE TITLE
Problem with Syntax

### ISSUE THREAD

**Issue by mpardina** [BorisNLatosh/FeynGrav#1]
Hello, I tried to run FeynGrav in Mathematica but the following code occurs:

Syntax::sntx: Invalid syntax in or before 
    "GaugeProjector = {\[Mu],\[Nu],k} |-> MTD[\[Mu],\[Nu]] - FVD[k,\[Mu]]"
        FVD[k,\[Nu]]/SPD[k,k] //Calc;
                                         ^
     (line 34 of "./Rules/Nieuwenhuizen.wl").

Syntax::sntx: Invalid syntax in or before 
    "DummyArray = n |->Flatten[                                                      "
        {ToExpression["m"<>ToString[#]],ToExpression["n"<>ToString[#]]}&/@Range[n] ];
                       ^
     (line 131 of "FeynGrav`").

Any idea? Thanks

**Comment by BorisNLatosh** [comment]
Hello. Please explain the situation in more detail.
What FeynGrav version do you use? When does this error occur?

**Comment by mpardina** [comment]
Hello. Sure: I am using FeynCalc 10.0 and FeynGrav 2.2, both latest
versions. The error emerges when I text " >>FeynGrav' " and I don't
understand why.
I am trying to use FeynGrav in order to calculate the 2->2 graviton
amplitude with fixed in helicities and general out helicities.

Thank you very much.

**Comment by BorisNLatosh** [comment]
Hello. Judging by the error messages, there are misprints in both of these files. Namely, it shall be "\[Mu]" and "\[Nu]", not "[Mu]" and "[Nu]". And it should be "Range", not "range".

However, I'm looking on the code present on GitHub and it does not have these misprints. 

It appears that files "./FeynGrav.wl" and "./Rules/Nieuwenhuizen.wl" are corrupted and I don't know why.

For the time being, please, replace your local files with those from GitHut and let me know if this fixed the problem. I also attach a copy of these files.
[Correct Files.zip](https://github.com/BorisNLatosh/FeynGrav/files/15006798/Correct.Files.zip)

**Comment by mpardina** [comment]
Hello.

Yes, the supposed misprints are correct in the .wl files, so I don't get
what is happening.
I have replaced the local files by the new ones you just send me and it
still doesn't work, I get the error message:

Syntax::sntx: Invalid syntax in or before "DummyArray = n |->Flatten[
***@***.***[n]
];" (line 131 of "FeynGrav`").

After compiling the cell two times, the first times it gives the same error
as before in line 34. This is very strange.

Thanks again for your help and time, I would really like to use FeynGrav
and it would help me a lot, but I don't understand this errors.

**Comment by BorisNLatosh** [comment]
Although the main code somehow ends up not working, you can still use expressions for graviton vertices.

".Libs/GravitonVertex_1", ".Libs/GravitonVertex_2", and ".Libs/GravitonVertex_3" contain expressions for 3-, 4-, and 5-graviton vertices. They are written in FeynCalc format and can be used without the main script. In these files, "m1","n1", "m2","n2", ... are indices of first, second, and other gravitons. "p1", "p2" are momenta of the same gravitons.

I will try to figure out why you get this error, but in the mean time you may try to use these expressions.

**Comment by mpardina** [comment]
Thank you so much, I will try to use the GravitonVertex libraries in order
to calculate my process.
If you find out why does the error occur, please let me know so I can fully
play with FeynGrav.

Thanks,
Miguel

**Comment by mpardina** [comment]
Dear Boris,

I have solved the problem reinstalling everything in Mathematica, so definitely it was my fault. If someone has a similar problem, just try to install everything again and it will probably work.
Now i have a physics question, in the page 13 of the paper [(https://arxiv.org/abs/2201.06812)] you give an expression for general 2->2 graviton scattering with helicities h1,...,h4, is the code of this calculation available? 

Thanks,
Miguel

**Comment by BorisNLatosh** [comment]
Dear Miguel,

I am glad to hear that you managed to solve the problem. I will close this issue then.

The code is available in one of the example files: FeynGrav/Examples/Graviton_Scattering_Tree_Level.nb.

Regards
Boris
